CREATE TABLE master (
	ID int NOT NULL primary key,
	R_fighter VARCHAR (60) NOT NULL,
	B_fighter VARCHAR (60) NOT NULL,
	Winner int NOT NULL,
	title_bout int NOT NULL,
	lose_streak_dif int NOT NULL,
	win_streak_dif int NOT NULL,
	longest_win_streak_dif int NOT NULL,
	win_dif int NOT NULL,
	loss_dif int NOT NULL,
	total_round_dif int NOT NULL,
	total_title_bout_dif int NOT NULL,
	ko_dif int NOT NULL,
	sub_dif int NOT NULL,
	height_dif float NOT NULL,
	reach_dif float NOT NULL,
	age_dif int NOT NULL,
	sig_str_dif float NOT NULL,
	avg_sub_att_dif float NOT NULL,
	avg_td_dif float NOT NULL,
	draw_diff int NOT NULL,
	avg_sig_str_pct_diff float NOT NULL,
	avg_TD_pct_diff float NOT NULL,
	win_by_Decision_Majority_diff int NOT NULL,
	win_by_Decision_Split_diff int NOT NULL,
	win_by_Decision_Unanimous_diff int NOT NULL,
	win_by_TKO_Doctor_Stoppage_diff int NOT NULL,
	odds_diff int NOT NULL,
	ev_diff float NOT NULL,
	kd_bout_diff float NOT NULL,
	sig_str_landed_bout_diff float NOT NULL,
	sig_str_attempted_bout_diff float NOT NULL,
	sig_str_pct_bout_diff float NOT NULL,
	tot_str_landed_bout_diff float NOT NULL,
	tot_str_attempted_bout_diff float NOT NULL,
	td_landed_bout_diff float NOT NULL,
	td_attempted_bout_diff float NOT NULL,
	td_pct_bout_diff float NOT NULL,
	sub_attempts_bout_diff float NOT NULL,
	pass_bout_diff float NOT NULL,
	rev_bout_diff float NOT NULL,
	Stance_diff int NOT NULL,
	better_rank_enc int NOT NULL
	);
