-- Create original table with na values filled
CREATE TABLE original (
	ID int NOT NULL primary key,
	R_fighter VARCHAR (30) NOT NULL,
	B_fighter VARCHAR (30) NOT NULL,
	R_odds int NOT NULL,
	B_odds int NOT NULL,
	R_ev float NOT NULL,
	B_ev float NOT NULL,
	date date NOT NULL,
	location varchar (30) NOT NULL,
	country varchar (30) NOT NULL,
	Winner varchar (30) NOT NULL,
	title_bout bool NOT NULL,
	weight_class varchar (30) NOT NULL,
	gender varchar (10) NOT NULL,
	no_of_rounds int NOT NULL,
	B_current_lose_streak int NOT NULL,
	B_current_win_streak int NOT NULL,
	B_draw int NOT NULL,
	B_avg_SIG_STR_landed float NOT NULL,
	B_avg_SIG_STR_pct float NOT NULL,
	B_avg_SUB_ATT float NOT NULL,
	B_avg_TD_landed float NOT NULL,
	B_avg_TD_pct float NOT NULL, 
	B_longest_win_streak int NOT NULL,
	B_losses int NOT NULL,
	B_total_rounds_fought int NOT NULL,
	B_total_title_bouts int NOT NULL,
	B_win_by_Decision_Majority int NOT NULL,
	B_win_by_Decision_Split int NOT NULL,
	B_win_by_Decision_Unanimous int NOT NULL,
	B_win_by_KO_TKO int NOT NULL,
	B_win_by_Submission int NOT NULL,
	B_win_by_TKO_Doctor_Stoppage int NOT NULL,
	B_wins int NOT NULL,
	B_Stance varchar (10) NOT NULL,
	B_Height_cms float NOT NULL,
	B_Reach_cms float NOT NULL,
	B_Weight_lbs int NOT NULL,
	R_current_lose_streak int NOT NULL,
	R_current_win_streak int NOT NULL,
	R_draw int NOT NULL,
	R_avg_SIG_STR_landed float NOT NULL,
	R_avg_SIG_STR_pct float NOT NULL,
	R_avg_SUB_ATT float NOT NULL,
	R_avg_TD_landed float NOT NULL,
	R_avg_TD_pct float NOT NULL,
	R_longest_win_streak int NOT NULL,
	R_losses int NOT NULL,
	R_total_rounds_fought int NOT NULL,
	R_total_title_bouts int NOT NULL,
	R_win_by_Decision_Majority int NOT NULL,
	R_win_by_Decision_Split int NOT NULL,
	R_win_by_Decision_Unanimous int NOT NULL,
	R_win_by_KO_TKO int NOT NULL,
	R_win_by_Submission int NOT NULL,
	R_win_by_TKO_Doctor_Stoppage int NOT NULL,
	R_wins int NOT NULL,
	R_Stance varchar (10) NOT NULL,
	R_Height_cms float NOT NULL,
	R_Reach_cms float NOT NULL,
	R_Weight_lbs int NOT NULL,
	R_age int NOT NULL,
	B_age int NOT NULL, 
	lose_streak_dif int NOT NULL,
	win_streak_dif int NOT NULL,
	longest_win_streak_dif int NOT NULL,
	win_dif int NOT NULL,
	loss_dif int NOT NULL,
	total_round_dif int NOT NULL,
	total_title_bout_dif int NOT NULL,
	ko_dif int NOT NULL,
	sub_dif int NOT NULL,
	height_dif float NOT NULL,
	reach_dif float NOT NULL,
	age_dif int NOT NULL,
	sig_str_dif float NOT NULL,
	avg_sub_att_dif float NOT NULL,
	avg_td_dif float NOT NULL,
	empty_arena int NOT NULL,
	constant_1 int NOT NULL
);
-- Create master table filled with preprocessed data
CREATE TABLE master (
	ID int NOT NULL primary key,
	R_fighter VARCHAR (60) NOT NULL,
	B_fighter VARCHAR (60) NOT NULL,
	Winner int NOT NULL,
	title_bout int NOT NULL,
	lose_streak_dif int NOT NULL,
	win_streak_dif int NOT NULL,
	longest_win_streak_dif int NOT NULL,
	win_dif int NOT NULL,
	loss_dif int NOT NULL,
	total_round_dif int NOT NULL,
	total_title_bout_dif int NOT NULL,
	ko_dif int NOT NULL,
	sub_dif int NOT NULL,
	height_dif float NOT NULL,
	reach_dif float NOT NULL,
	age_dif int NOT NULL,
	sig_str_dif float NOT NULL,
	avg_sub_att_dif float NOT NULL,
	avg_td_dif float NOT NULL,
	draw_diff int NOT NULL,
	avg_sig_str_pct_diff float NOT NULL,
	avg_TD_pct_diff float NOT NULL,
	win_by_Decision_Majority_diff int NOT NULL,
	win_by_Decision_Split_diff int NOT NULL,
	win_by_Decision_Unanimous_diff int NOT NULL,
	win_by_TKO_Doctor_Stoppage_diff int NOT NULL,
	odds_diff int NOT NULL,
	ev_diff float NOT NULL,
	kd_bout_diff float NOT NULL,
	sig_str_landed_bout_diff float NOT NULL,
	sig_str_attempted_bout_diff float NOT NULL,
	sig_str_pct_bout_diff float NOT NULL,
	tot_str_landed_bout_diff float NOT NULL,
	tot_str_attempted_bout_diff float NOT NULL,
	td_landed_bout_diff float NOT NULL,
	td_attempted_bout_diff float NOT NULL,
	td_pct_bout_diff float NOT NULL,
	sub_attempts_bout_diff float NOT NULL,
	pass_bout_diff float NOT NULL,
	rev_bout_diff float NOT NULL,
	Stance_diff int NOT NULL,
	better_rank_enc int NOT NULL
	);
-- Left Join the two tables in order to show a comparison of "tale of the tape" stats vs the stats we found to correlate to wins most
SELECT original.R_fighter, original.B_fighter, original.gender, original.R_age, original.B_age, original.R_Height_cms, original.B_Height_cms, original.R_Weight_lbs, original.B_Weight_lbs, original.R_Reach_cms, original.R_Reach_cms, master.sig_str_landed_bout_diff, master.ev_diff, master.odds_diff, master.tot_str_landed_bout_diff, master.sig_str_pct_bout_diff
FROM original
LEFT JOIN master ON original.ID = master.ID
;
